name: SampleSolution
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  - matplotlib=3.4.3
  - numpy=1.21.2
  - pillow>=8.1.2
  - pyyaml=5.4.1
  - scipy=1.7.1
  - tensorboard
  - tqdm=4.62.1

  - seaborn=0.11.2
  - pandas=1.3.2
  - easydict
  
  - pip:
    # - torch==1.8.0 -f https://download.pytorch.org/whl/torch_stable.html
    # - torchvision==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
    - torch-1.8.0a0-cp37-cp37m-linux_aarch64.whl
    - torchvision-0.8.0a0+45f960c-cp37-cp37m-linux_aarch64.whl
    - opencv-contrib-python-headless>=4.1.2
