DEEPSORT:
  REID_CKPT: 'deep_sort/deep_sort/deep/checkpoint/ckpt.t7' # "weights/deepsort-deep-checkpoint.t7"
  MAX_DIST: 0.6 #0.2
  MIN_CONFIDENCE: 0.2 #0.2
  NMS_MAX_OVERLAP: 0.9 #0.75
  MAX_IOU_DISTANCE: 0.1 #0.7
  MAX_AGE: 70
  N_INIT: 3 #3
  NN_BUDGET: 100 #100
  
